# shellcheck shell=bash
#
# vpnscript -- server side helper library.
#
# This file is never installed on the server. install.sh / add.sh / remove.sh
# concatenate it with an operation payload and pipe the result into
# `ssh <target> bash -s`, so everything here runs on the VPN server itself.

set -euo pipefail
umask 077

VS_DIR=/etc/vpnscript
VS_STATE="$VS_DIR/server.env"
AWG_ETC=/etc/amnezia/amneziawg
XRAY_ETC=/usr/local/etc/xray
XRAY_CONF="$XRAY_ETC/config.json"
XRAY_BIN=/usr/local/bin/xray
XRAY_ASSETS=/usr/local/share/xray
AWG_GO_BIN=/usr/local/bin/amneziawg-go

: "${VS_COLOR:=0}"
if [ "$VS_COLOR" = 1 ]; then
	C_B=$'\033[1;34m'; C_G=$'\033[1;32m'; C_Y=$'\033[1;33m'; C_R=$'\033[1;31m'; C_0=$'\033[0m'
else
	C_B=; C_G=; C_Y=; C_R=; C_0=
fi

# All human readable output goes to stderr; stdout carries the file payload.
log()  { printf '%s::%s %s\n'  "$C_B" "$C_0" "$*" >&2; }
ok()   { printf '%s ok%s %s\n' "$C_G" "$C_0" "$*" >&2; }
warn() { printf '%s !!%s %s\n' "$C_Y" "$C_0" "$*" >&2; }
die()  { printf '%s xx%s %s\n' "$C_R" "$C_0" "$*" >&2; exit 1; }

# ---------------------------------------------------------------- file payload

# emit <filename>  -- reads file body from stdin, wraps it in markers that the
# local splitter understands. The body must end with a newline.
emit() {
	printf '__VPNSCRIPT_FILE__ %s\n' "$1"
	cat
	printf '__VPNSCRIPT_EOF__\n'
}

# ------------------------------------------------------------------- randomness

# rnd MIN MAX -- uniform-ish integer in [MIN, MAX]
rnd() {
	local min=$1 max=$2 span v
	span=$(( max - min + 1 ))
	v=$(od -An -N4 -tu4 < /dev/urandom | tr -d ' \n')
	printf '%s\n' "$(( min + v % span ))"
}

rand_hex() { head -c "$1" /dev/urandom | od -An -v -tx1 | tr -d ' \n'; }

# A URL path that looks like an ordinary web app endpoint.
rand_path() { printf '/%s\n' "$(head -c 12 /dev/urandom | od -An -v -tx1 | tr -d ' \n' | cut -c1-16)"; }

# ------------------------------------------------------------------------ ports

port_taken() {
	ss -H -lntu 2>/dev/null | awk '{print $5}' | sed 's/.*://' | grep -qx "$1"
}

# pick_port -- an unused port in the 1200-2000 range
pick_port() {
	local p i=0
	while [ "$i" -lt 300 ]; do
		p=$(rnd 1200 2000)
		if ! port_taken "$p"; then printf '%s\n' "$p"; return 0; fi
		i=$(( i + 1 ))
	done
	die "could not find a free port in 1200-2000"
}

# ------------------------------------------------------------------------ state

vs_load_state() {
	[ -r "$VS_STATE" ] || die "$VS_STATE not found -- run install.sh against this host first"
	# shellcheck disable=SC1090
	. "$VS_STATE"
	local v
	for v in VS_ENDPOINT VS_AWG_IF VS_AWG_PORT VS_AWG_PUB VS_NET4_PREFIX VS_DNS_IP \
		VS_MTU VS_HAS_V6 VS_XRAY_PORT VS_XRAY_TAG VS_REALITY_PBK VS_REALITY_SID VS_XHTTP_PATH; do
		[ -n "${!v:-}" ] || die "$VS_STATE is incomplete (no $v) -- reinstall with: install.sh --force"
	done
}

vs_save_state() {
	local tmp
	tmp=$(mktemp "$VS_DIR/.server.env.XXXXXX")
	{
		printf '# Generated by vpnscript. Do not edit while clients are connected.\n'
		local k
		for k in VS_VERSION VS_ENDPOINT VS_AWG_IF VS_AWG_PORT VS_AWG_PUB \
			VS_NET4 VS_NET4_PREFIX VS_NET6 VS_NET6_PREFIX VS_HAS_V6 VS_DNS_IP VS_DNS_IP6 VS_MTU \
			VS_JC VS_JMIN VS_JMAX VS_S1 VS_S2 VS_S3 VS_S4 VS_H1 VS_H2 VS_H3 VS_H4 VS_I1 \
			VS_XRAY_PORT VS_XRAY_TAG VS_REALITY_SNI VS_REALITY_PBK VS_REALITY_SID \
			VS_XHTTP_PATH VS_DOH; do
			printf "%s='%s'\n" "$k" "${!k}"
		done
	} > "$tmp"
	chmod 600 "$tmp"
	mv "$tmp" "$VS_STATE"
}

# -------------------------------------------------------------- client registry
#
# The server keeps no client configuration files. The only per-client state that
# survives on the server is what the two daemons need in order to accept the
# client: a WireGuard peer (public key + preshared key + tunnel address) in
# awg0.conf, and a VLESS user (uuid + email) in the Xray config. Private keys
# are generated, handed to the client and dropped.

vs_awg_conf() { printf '%s/%s.conf\n' "$AWG_ETC" "$VS_AWG_IF"; }

vs_name_valid() {
	case $1 in
		''|*[!A-Za-z0-9._-]*) return 1 ;;
		*) return 0 ;;
	esac
}

vs_awg_has_client() { grep -qF "# vpnscript-peer name=$1 " "$(vs_awg_conf)" 2>/dev/null; }

vs_xray_has_client() {
	jq -e --arg e "$1" --arg t "$VS_XRAY_TAG" \
		'any(.inbounds[]? | select(.tag == $t) | .settings.clients[]?; .email == $e)' \
		"$XRAY_CONF" >/dev/null 2>&1
}

vs_client_exists() {
	if vs_awg_has_client "$1"; then return 0; fi
	if vs_xray_has_client "$1"; then return 0; fi
	return 1
}

vs_list_clients() {
	{
		sed -n 's/^# vpnscript-peer name=\([^ ]*\) .*/\1/p' "$(vs_awg_conf)" 2>/dev/null || true
		jq -r --arg t "$VS_XRAY_TAG" \
			'.inbounds[]? | select(.tag == $t) | .settings.clients[]?.email // empty' \
			"$XRAY_CONF" 2>/dev/null || true
	} | sort -u
}

# Lowest free host number in the tunnel subnet (2-254; .1 is the server).
vs_next_index() {
	local used i
	used=$(sed -n 's/^# vpnscript-peer .*idx=\([0-9]*\).*/\1/p' "$(vs_awg_conf)" 2>/dev/null || true)
	for i in $(seq 2 254); do
		if ! printf '%s\n' "$used" | grep -qx "$i"; then printf '%s\n' "$i"; return 0; fi
	done
	die "tunnel address pool exhausted (254 clients)"
}

# ------------------------------------------------------------- config rendering

# vs_render_awg_client NAME IDX PRIVKEY PSK
vs_render_awg_client() {
	local name=$1 idx=$2 priv=$3 psk=$4 addr dns
	addr="${VS_NET4_PREFIX}.${idx}/32"
	dns="$VS_DNS_IP"
	if [ "$VS_HAS_V6" = 1 ]; then addr="${addr}, ${VS_NET6_PREFIX}${idx}/128"; fi
	cat <<EOF
# vpnscript-client = $name
# vpnscript-server = $VS_ENDPOINT
#
# AmneziaWG 2.0 profile. Import it into the AmneziaVPN app (4.8.12.9+), or on
# Linux drop it in /etc/amnezia/amneziawg/ and run: awg-quick up $name
# DNS resolves inside the tunnel and is forwarded upstream over DNS-over-HTTPS.
[Interface]
PrivateKey = $priv
Address = $addr
DNS = $dns
MTU = $VS_MTU
Jc = $VS_JC
Jmin = $VS_JMIN
Jmax = $VS_JMAX
S1 = $VS_S1
S2 = $VS_S2
S3 = $VS_S3
S4 = $VS_S4
H1 = $VS_H1
H2 = $VS_H2
H3 = $VS_H3
H4 = $VS_H4
I1 = $VS_I1

[Peer]
PublicKey = $VS_AWG_PUB
PresharedKey = $psk
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = $VS_ENDPOINT:$VS_AWG_PORT
PersistentKeepalive = 25
EOF
}

# vs_render_vless_url NAME UUID
vs_render_vless_url() {
	local name=$1 uuid=$2 path frag
	path=$(jq -rn --arg s "$VS_XHTTP_PATH" '$s|@uri')
	frag=$(jq -rn --arg s "$name" '$s|@uri')
	printf 'vless://%s@%s:%s?encryption=none&security=reality&sni=%s&fp=chrome&pbk=%s&sid=%s&type=xhttp&path=%s&mode=auto#%s\n' \
		"$uuid" "$VS_ENDPOINT" "$VS_XRAY_PORT" "$VS_REALITY_SNI" \
		"$VS_REALITY_PBK" "$VS_REALITY_SID" "$path" "$frag"
}

# vs_render_xray_client NAME UUID
vs_render_xray_client() {
	local name=$1 uuid=$2 qs=UseIPv4
	if [ "$VS_HAS_V6" = 1 ]; then qs=UseIP; fi
	jq -n \
		--arg name "$name" --arg uuid "$uuid" --arg host "$VS_ENDPOINT" \
		--argjson port "$VS_XRAY_PORT" --arg sni "$VS_REALITY_SNI" \
		--arg pbk "$VS_REALITY_PBK" --arg sid "$VS_REALITY_SID" \
		--arg path "$VS_XHTTP_PATH" --arg dns "$VS_DNS_IP" --arg qs "$qs" \
		--arg url "$(vs_render_vless_url "$name" "$uuid")" '
{
  "_vpnscript_client": $name,
  "_comment": "vpnscript client \($name). Share link: \($url)",
  "log": { "loglevel": "warning" },
  "dns": { "servers": [ $dns ], "queryStrategy": $qs },
  "inbounds": [
    { "tag": "socks-in", "listen": "127.0.0.1", "port": 10808, "protocol": "socks",
      "settings": { "udp": true },
      "sniffing": { "enabled": true, "destOverride": [ "http", "tls", "quic" ] } },
    { "tag": "http-in", "listen": "127.0.0.1", "port": 10809, "protocol": "http" }
  ],
  "outbounds": [
    { "tag": "proxy", "protocol": "vless",
      "settings": { "vnext": [ { "address": $host, "port": $port,
        "users": [ { "id": $uuid, "encryption": "none" } ] } ] },
      "streamSettings": { "network": "xhttp", "security": "reality",
        "realitySettings": { "serverName": $sni, "fingerprint": "chrome",
          "publicKey": $pbk, "shortId": $sid, "spiderX": "/" },
        "xhttpSettings": { "path": $path, "mode": "auto" } } },
    { "tag": "direct", "protocol": "freedom" },
    { "tag": "block", "protocol": "blackhole" }
  ],
  "routing": { "domainStrategy": "AsIs",
    "rules": [ { "type": "field", "inboundTag": [ "socks-in", "http-in" ], "outboundTag": "proxy" } ] }
}'
}

# ------------------------------------------------------------- add/remove hooks

# vs_add_client NAME -- registers the client with both daemons and writes the
# three client files to the payload stream. Nothing is stored on disk here.
vs_add_client() {
	local name=$1 idx priv pub psk uuid conf
	vs_name_valid "$name" || die "invalid client name '$name' (use A-Z a-z 0-9 . _ -)"
	if vs_client_exists "$name"; then die "client '$name' already exists"; fi

	conf=$(vs_awg_conf)
	idx=$(vs_next_index)
	priv=$(awg genkey)
	pub=$(printf '%s\n' "$priv" | awg pubkey)
	psk=$(awg genpsk)

	{
		printf '\n# vpnscript-peer name=%s idx=%s\n' "$name" "$idx"
		printf '[Peer]\n'
		printf 'PublicKey = %s\n' "$pub"
		printf 'PresharedKey = %s\n' "$psk"
		if [ "$VS_HAS_V6" = 1 ]; then
			printf 'AllowedIPs = %s.%s/32, %s%s/128\n' "$VS_NET4_PREFIX" "$idx" "$VS_NET6_PREFIX" "$idx"
		else
			printf 'AllowedIPs = %s.%s/32\n' "$VS_NET4_PREFIX" "$idx"
		fi
	} >> "$conf"

	uuid=$("$XRAY_BIN" uuid)
	vs_xray_edit --arg id "$uuid" --arg em "$name" --arg t "$VS_XRAY_TAG" \
		'(.inbounds[] | select(.tag == $t) | .settings.clients) += [ { "id": $id, "email": $em } ]'

	vs_render_awg_client  "$name" "$idx" "$priv" "$psk" | emit "$name.conf"
	vs_render_xray_client "$name" "$uuid"               | emit "$name.xray.json"
	vs_render_vless_url   "$name" "$uuid"               | emit "$name.vless.url"

	log "added client '$name' (tunnel ip ${VS_NET4_PREFIX}.${idx}, vless uuid ${uuid%%-*}-...)"
}

# vs_remove_awg_peer <matcher> -- deletes the peer block containing <matcher>.
# awg0.conf is written so that every peer is one blank-line separated paragraph,
# which lets awk drop a whole block by substring match.
vs_remove_awg_peer() {
	local m=$1 conf tmp
	conf=$(vs_awg_conf)
	grep -qF "$m" "$conf" 2>/dev/null || return 1
	tmp=$(mktemp)
	awk -v m="$m" 'BEGIN { RS = ""; ORS = "\n\n" } index($0, m) == 0' "$conf" > "$tmp"
	chmod 600 "$tmp"
	mv "$tmp" "$conf"
	return 0
}

vs_remove_xray_client() { # vs_remove_xray_client email|uuid VALUE
	local field=$1 value=$2 before after
	before=$(jq --arg t "$VS_XRAY_TAG" '[.inbounds[] | select(.tag == $t) | .settings.clients[]?] | length' "$XRAY_CONF")
	if [ "$field" = email ]; then
		vs_xray_edit --arg v "$value" --arg t "$VS_XRAY_TAG" \
			'(.inbounds[] | select(.tag == $t) | .settings.clients) |= map(select(.email != $v))'
	else
		vs_xray_edit --arg v "$value" --arg t "$VS_XRAY_TAG" \
			'(.inbounds[] | select(.tag == $t) | .settings.clients) |= map(select(.id != $v))'
	fi
	after=$(jq --arg t "$VS_XRAY_TAG" '[.inbounds[] | select(.tag == $t) | .settings.clients[]?] | length' "$XRAY_CONF")
	[ "$before" != "$after" ]
}

# vs_xray_edit <jq args...> <filter> -- applies a jq filter to the Xray config,
# validates the result with `xray run -test` and only then swaps it in.
vs_xray_edit() {
	local tmp
	tmp=$(mktemp "$XRAY_ETC/.config.json.XXXXXX")
	if ! jq "$@" "$XRAY_CONF" > "$tmp"; then
		rm -f "$tmp"
		die "failed to edit $XRAY_CONF"
	fi
	chmod 640 "$tmp"
	chown root:xray "$tmp" 2>/dev/null || true
	# -format is explicit: the temp file has no .json extension for Xray to sniff.
	if ! "$XRAY_BIN" run -test -format json -config "$tmp" >/dev/null 2>&1; then
		local err
		err=$("$XRAY_BIN" run -test -format json -config "$tmp" 2>&1 | tail -5 || true)
		rm -f "$tmp"
		die "generated Xray config is invalid: $err"
	fi
	mv "$tmp" "$XRAY_CONF"
}

# ------------------------------------------------------------------ apply/reload

vs_apply_awg() {
	if ip link show "$VS_AWG_IF" >/dev/null 2>&1; then
		awg syncconf "$VS_AWG_IF" <(awg-quick strip "$VS_AWG_IF")
	else
		systemctl start "awg-quick@$VS_AWG_IF"
	fi
}

vs_apply_xray() {
	systemctl restart xray
	sleep 1
	systemctl is-active --quiet xray || die "xray failed to restart: $(journalctl -u xray -n 15 --no-pager 2>&1 | tail -15)"
}
